"Protect from self-destruct."

diff --git a/prepare b/prepare
--- a/prepare
+++ b/prepare
@@ -2,10 +2,18 @@
 
 # Install Software-Toolkit if not available - Via Dependable?
 
+HERE=$(pwd)
+
 if [ -z "$SUBMODULES_HOME" ]; then
 
   echo "ERROR: The SUBMODULES_HOME is not defined !!!"
   exit 1
+fi
+
+if [ "$HERE" == "$SUBMODULES_HOME" ]; then
+
+    echo "ERROR: Forbidden inoking from '$HERE'"
+    exit 1
 fi
 
 SCRIPT_PREPARE="$SUBMODULES_HOME/Project/prepare.sh"
@@ -25,8 +33,6 @@ fi
 
 # shellcheck disable=SC1090
 . "$SCRIPT_PATHS"
-
-HERE=$(dirname "$(realpath "$0")")
 
 if ! sh "$SCRIPT_PREPARE" "$HERE"; then
 
